"""initial schema (ADR-0006)

Revision ID: 6342d9aafe6f
Revises: 
Create Date: 2026-08-07 21:41:47.479319
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '6342d9aafe6f'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_fundamentals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('sector', sa.String(length=128), nullable=False),
    sa.Column('industry', sa.String(length=128), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('net_income', sa.Float(), nullable=True),
    sa.Column('eps', sa.Float(), nullable=True),
    sa.Column('assets', sa.Float(), nullable=True),
    sa.Column('liabilities', sa.Float(), nullable=True),
    sa.Column('cash_flow', sa.Float(), nullable=True),
    sa.Column('equity', sa.Float(), nullable=True),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('retrieval_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_company_fundamentals_symbol_report', 'company_fundamentals', ['symbol', 'report_date'], unique=False)
    op.create_table('event_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_index('ix_event_logs_source_type', 'event_logs', ['source', 'event_type'], unique=False)
    op.create_index('ix_event_logs_timestamp', 'event_logs', ['timestamp'], unique=False)
    op.create_table('market_candles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.Enum('1m', '5m', '15m', '30m', '1h', '4h', '1d', '1w', '1mo', name='timeframe', native_enum=False), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('vwap', sa.Float(), nullable=True),
    sa.Column('trade_count', sa.Integer(), nullable=True),
    sa.Column('average_price', sa.Float(), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'timeframe', 'timestamp', name='uq_market_candles_symbol_timeframe_timestamp')
    )
    op.create_index('ix_market_candles_symbol_timeframe', 'market_candles', ['symbol', 'timeframe'], unique=False)
    op.create_table('securities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('exchange', sa.String(length=32), nullable=False),
    sa.Column('asset_type', sa.Enum('equity', name='asset_type', native_enum=False), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('trading_session', sa.String(length=32), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('market_status', sa.Enum('open', 'closed', 'halted', 'suspended', name='market_status', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'exchange', name='uq_securities_symbol_exchange')
    )
    op.create_table('shariah_securities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('exchange', sa.String(length=32), nullable=False),
    sa.Column('country', sa.String(length=64), nullable=False),
    sa.Column('asset_type', sa.Enum('equity', name='asset_type', native_enum=False), nullable=False),
    sa.Column('compliance_status', sa.Enum('compliant', 'non_compliant', 'under_review', 'unknown', name='compliance_status', native_enum=False), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('provider_version', sa.String(length=32), nullable=False),
    sa.Column('review_date', sa.Date(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('screening_methodology', sa.String(length=255), nullable=False),
    sa.Column('screening_version', sa.String(length=32), nullable=False),
    sa.Column('screening_date', sa.Date(), nullable=False),
    sa.Column('confidence_level', sa.Float(), nullable=False),
    sa.Column('previous_status', sa.Enum('compliant', 'non_compliant', 'under_review', 'unknown', name='previous_status', native_enum=False), nullable=True),
    sa.Column('retrieval_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_shariah_securities_symbol_effective', 'shariah_securities', ['symbol', 'effective_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_shariah_securities_symbol_effective', table_name='shariah_securities')
    op.drop_table('shariah_securities')
    op.drop_table('securities')
    op.drop_index('ix_market_candles_symbol_timeframe', table_name='market_candles')
    op.drop_table('market_candles')
    op.drop_index('ix_event_logs_timestamp', table_name='event_logs')
    op.drop_index('ix_event_logs_source_type', table_name='event_logs')
    op.drop_table('event_logs')
    op.drop_index('ix_company_fundamentals_symbol_report', table_name='company_fundamentals')
    op.drop_table('company_fundamentals')
    # ### end Alembic commands ###
